### LOGIN
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "admin", "password":"admin"}

### SIGNUP 

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"Rakshit", "password":"test", "email":"rakshit3raj@gmail.com"}

### TEST TOKEN

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### SET POLYGON

POST http://127.0.0.1:8000/field/set_field
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{
  "polygon": {
    "type": "Polygon",
    "coordinates": [
      [
        [77.2090, 28.6139],
        [77.2290, 28.6139],
        [77.2290, 28.6339],
        [77.2090, 28.6339],
        [77.2090, 28.6139]
      ]
    ]
  },
  "cropType": "Wheat"
}

### EE SATELLITE DATA

GET http://127.0.0.1:8000/field/ee
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### GET COORDS
GET http://127.0.0.1:8000/field/coord
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### PEST DETECTION

POST http://127.0.0.1:8000/pest
Authorization: Token d5168cd4b604859db241e89734016b806393e69f
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="sample.jpg"
Content-Type: image/jpeg

< ./sample.jpg
--WebAppBoundary--

### AWD REPORT
GET http://127.0.0.1:8000/field/awd
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### Carbon Credit
GET http://127.0.0.1:8000/field/cc
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### Pest Prediction
GET http://127.0.0.1:8000/field/pestpredict
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}

### Health Score
GET http://127.0.0.1:8000/field/healthscore
Content-Type: application/json
Authorization: Token d5168cd4b604859db241e89734016b806393e69f

{}